export {
  DELIVERY_NOTE_DEDUCTS_STOCK,
  DELIVERY_NOTE_DEFAULT_STATUS_FLOW,
  DELIVERY_NOTE_STAGE_CATALOGUE,
  DELIVERY_NOTE_STAGE_COLORS,
  GOODS_RECEIPT_DEFAULT_STATUS_FLOW,
  GOODS_RECEIPT_STAGE_CATALOGUE,
  GOODS_RECEIPT_STAGE_COLORS,
  SALES_ORDER_DEFAULT_STATUS_FLOW,
  SALES_ORDER_LOCKS_STOCK,
  SALES_ORDER_STAGE_CATALOGUE,
  SALES_ORDER_STAGE_COLORS,
  canTransition,
  resolveStatusFlow,
  statusHasCapability,
  statusOf,
  transitionsFrom,
  validateStatusFlow,
} from './__internal__/credo-sme/status-flow';
export type {
  DeliveryNoteStage,
  GoodsReceiptStage,
  SalesOrderStage,
  StageCatalogue,
  StatusCapability,
  StatusFlowConfig,
  StatusFlowStatus,
  StatusFlowTransition,
  StatusFlowValidation,
  TransitionContext,
  TransitionDenial,
  TransitionVerdict,
} from './__internal__/credo-sme/status-flow';
