import {
  IconAffiliate,
  IconUserShare,
  IconLayersLinked,
  IconReplace,
  IconActivity,
  IconAlertTriangle,
  IconArrowLeft,
  IconArrowsExchange,
  IconDots,
  IconBell,
  IconBox,
  IconCaretDownFilled,
  IconCategory,
  IconCategory2,
  IconCheck,
  IconChevronDown,
  IconBuildingWarehouse,
  IconClipboardList,
  IconClock,
  IconDatabase,
  IconDownload,
  IconFileOff,
  IconFileSpreadsheet,
  IconFileText,
  IconHome,
  IconKey,
  IconLanguage,
  IconLock,
  IconLogout,
  IconMail,
  IconMenu2,
  IconMoon,
  IconPackage,
  IconPackageExport,
  IconPackageImport,
  IconQrcode,
  IconRefresh,
  IconReportAnalytics,
  IconRuler,
  IconServer,
  IconSettings,
  IconShield,
  IconShoppingCart,
  IconSun,
  IconStack2,
  IconTool,
  IconTruck,
  IconTruckDelivery,
  IconUser,
  IconUsers,
  IconWorld,
  IconX,
} from '@tabler/icons-react';

export enum IconName {
  Affiliate = 'IconAffiliate',
  UserShare = 'IconUserShare',
  LayersLinked = 'IconLayersLinked',
  Activity = 'IconActivity',
  AlertTriangle = 'IconAlertTriangle',
  ArrowLeft = 'IconArrowLeft',
  ArrowsExchange = 'IconArrowsExchange',
  Bell = 'IconBell',
  Box = 'IconBox',
  BuildingWarehouse = 'IconBuildingWarehouse',
  CaretDownFilled = 'IconCaretDownFilled',
  Category = 'IconCategory',
  Category2 = 'IconCategory2',
  Check = 'IconCheck',
  ChevronDown = 'IconChevronDown',
  ClipboardList = 'IconClipboardList',
  Clock = 'IconClock',
  Database = 'IconDatabase',
  Dots = 'IconDots',
  Download = 'IconDownload',
  FileOff = 'IconFileOff',
  FileSpreadsheet = 'IconFileSpreadsheet',
  FileText = 'IconFileText',
  Home = 'IconHome',
  Key = 'IconKey',
  Language = 'IconLanguage',
  Lock = 'IconLock',
  Logout = 'IconLogout',
  Mail = 'IconMail',
  Menu2 = 'IconMenu2',
  Moon = 'IconMoon',
  Package = 'IconPackage',
  PackageExport = 'IconPackageExport',
  PackageImport = 'IconPackageImport',
  Qrcode = 'IconQrcode',
  Refresh = 'IconRefresh',
  Replace = 'IconReplace',
  ReportAnalytics = 'IconReportAnalytics',
  Ruler = 'IconRuler',
  Server = 'IconServer',
  Settings = 'IconSettings',
  Shield = 'IconShield',
  ShoppingCart = 'IconShoppingCart',
  Stack2 = 'IconStack2',
  Sun = 'IconSun',
  Tool = 'IconTool',
  Truck = 'IconTruck',
  TruckDelivery = 'IconTruckDelivery',
  User = 'IconUser',
  Users = 'IconUsers',
  World = 'IconWorld',
  X = 'IconX',
}

export const ICON_MAP: Record<IconName, typeof IconBox> = {
  [IconName.Affiliate]: IconAffiliate,
  [IconName.UserShare]: IconUserShare,
  [IconName.LayersLinked]: IconLayersLinked,
  [IconName.Activity]: IconActivity,
  [IconName.AlertTriangle]: IconAlertTriangle,
  [IconName.ArrowLeft]: IconArrowLeft,
  [IconName.ArrowsExchange]: IconArrowsExchange,
  [IconName.Bell]: IconBell,
  [IconName.Box]: IconBox,
  [IconName.BuildingWarehouse]: IconBuildingWarehouse,
  [IconName.CaretDownFilled]: IconCaretDownFilled,
  [IconName.Category]: IconCategory,
  [IconName.Category2]: IconCategory2,
  [IconName.Check]: IconCheck,
  [IconName.ChevronDown]: IconChevronDown,
  [IconName.ClipboardList]: IconClipboardList,
  [IconName.Clock]: IconClock,
  [IconName.Database]: IconDatabase,
  [IconName.Dots]: IconDots,
  [IconName.Download]: IconDownload,
  [IconName.FileOff]: IconFileOff,
  [IconName.FileSpreadsheet]: IconFileSpreadsheet,
  [IconName.FileText]: IconFileText,
  [IconName.Home]: IconHome,
  [IconName.Key]: IconKey,
  [IconName.Language]: IconLanguage,
  [IconName.Lock]: IconLock,
  [IconName.Logout]: IconLogout,
  [IconName.Mail]: IconMail,
  [IconName.Menu2]: IconMenu2,
  [IconName.Moon]: IconMoon,
  [IconName.Package]: IconPackage,
  [IconName.PackageExport]: IconPackageExport,
  [IconName.PackageImport]: IconPackageImport,
  [IconName.Qrcode]: IconQrcode,
  [IconName.Refresh]: IconRefresh,
  [IconName.Replace]: IconReplace,
  [IconName.ReportAnalytics]: IconReportAnalytics,
  [IconName.Ruler]: IconRuler,
  [IconName.Server]: IconServer,
  [IconName.Settings]: IconSettings,
  [IconName.Shield]: IconShield,
  [IconName.ShoppingCart]: IconShoppingCart,
  [IconName.Stack2]: IconStack2,
  [IconName.Sun]: IconSun,
  [IconName.Tool]: IconTool,
  [IconName.Truck]: IconTruck,
  [IconName.TruckDelivery]: IconTruckDelivery,
  [IconName.User]: IconUser,
  [IconName.Users]: IconUsers,
  [IconName.World]: IconWorld,
  [IconName.X]: IconX,
};
